config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles # only: [:create, :index, :destroy]

  # get "articles", to: "articles#index" # READ ALL

  # get "articles/:id", to: "articles#show", as: :article
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new 
  end

  def create
    @article = Article.new(article_params)
    @article.save

    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= form_for(@article) do |a| %>
  <%= a.label :title %>
  <%= a.text_field :title %>
  <%= a.label :content %>
  <%= a.text_field :content %>
  <%= a.submit %>
<% end %>


app/views/articles/index.html.erb
<ul>
	<% @articles.each do |article| %>
		<li><%= link_to article.title, article_path(article) %> - <%= article.content %></li>
	<% end %>
</ul>

app/views/articles/new.html.erb
<%= form_for(@article) do |a| %>
  <%= a.label :title %>
  <%= a.text_field :title %>
  <%= a.label :content %>
  <%= a.text_field :content %>
  <%= a.submit %>
<% end %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
<p><%= @article.content %></p>



<%= link_to "Delete #{@article.title}",
            article_path(@article),
            method: :delete,
            data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav">
      <%= link_to "Index", articles_path %>
      <%= link_to "new", new_article_path %>
    </div>
    <%= yield %>
  </body>
</html>